<?php
$css=array(
    'font-awesome',
    'animate',    
    'bootstrap.min',
    'jquery-ui',
    'magnific-popup',
    'jAlert-v3',
    'layerslider',
    'webslidemenu',
    'flexslider',
    'self'
);
$js=array(
    'jquery',
    'jquery-ui',
    'jquery-migrate',
    'bootstrap.min',
    'validator.min',
    'jquery.magnific-popup',
    'jAlert-v3',
    'jAlert-functions',
    'layerslider',
    'layerslider.greensock',
    'layerslider.transitions',
    'wow',
    'webslidemenu',
    'jquery.flexslider', 
    'self'
);
include_once 'config.php';
include_once 'lang/'.$lang.'.php';
define('limit',10);
define('pd_lim',16);
?>